### ISSUE TITLE
Unable to run first `cdk bootstrap`

### ISSUE THREAD

**Issue by gergnz** [sktan/snapsecret#1]
`npm run bootstrap`
...
...
```
Traceback (most recent call last):
  File "/Users/gregc/Scratch/dev/gergnz/snapsecret/cdk/app.py", line 16, in <module>
    frontend = FrontendStack(
  File "/Users/gregc/.local/share/virtualenvs/cdk-DoTih0IL/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/gregc/Scratch/dev/gergnz/snapsecret/cdk/snapsecret/frontend_stack.py", line 36, in __init__
    apigw_url = boto3.client("ssm").get_parameter(Name=paramstore_path)[
  File "/Users/gregc/.local/share/virtualenvs/cdk-DoTih0IL/lib/python3.9/site-packages/botocore/client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/gregc/.local/share/virtualenvs/cdk-DoTih0IL/lib/python3.9/site-packages/botocore/client.py", line 745, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ParameterNotFound: An error occurred (ParameterNotFound) when calling the GetParameter operation:

Subprocess exited with error 1
```

**Comment by sktan** [comment]
Looks like an oversight with the way the bootstrap command works, I've added a workaround that solves this by failing to a temporary variable if SSM couldn't be resolved (bit of an initial hacky workaround, as until the backend stack is built, we can't determine what the API GW domain is, which is important for the frontend to be built).

Thanks for that @gergnz
